SET SEARCH_PATH = HIPERMERCADO;

-- Consultas:

-- a. Informe o CPF e o nome dos clientes que efetuaram uma transação maior
-- que R\$ 700,00 com atendentes com nome de Maria utilizando cupons de
-- 30\% ou mais de desconto.

SELECT CLI.CPF, CLI.NOME_CLIENTE
FROM CLIENTE CLI
JOIN COMPRA CMP ON CMP.CPF_CLIENTE = CLI.CPF
JOIN ATENDENTE_CAIXA AC ON AC.CPF_FUNCIONARIO = CMP.CPF_ATENDENTE
JOIN FUNCIONARIO FNC ON FNC.CPF = AC.CPF_FUNCIONARIO
WHERE CMP.VALOR_TOTAL > 700 AND
	  CMP.VALOR_TOTAL_DESCONTO >= 700 - (0.3 * 700);


-- b. Informe o CPF do atendente, CPF do cliente, a nota de atendimento e a
-- descrição da avaliação das compras cujos atendentes possuem média de
-- nota de atendimento maior que 6.

SELECT ATC.CPF_FUNCIONARIO, CLI.CPF, AVL.NOTA_ATENDIMENTO, AVL.DESCRICAO
FROM ATENDENTE_CAIXA ATC, CLIENTE CLI, AVALIACAO AVL, COMPRA CMP
WHERE AVL.CPF_CLIENTE = CLI.CPF AND
CMP.CPF_CLIENTE = CLI.CPF AND
CMP.CPF_ATENDENTE = ATC.CPF_FUNCIONARIO AND
AVL.NRO_CUPOM_FISCAL = CMP.NRO_CUPOM_FISCAL
GROUP BY (ATC.CPF_FUNCIONARIO, CLI.CPF, AVL.NOTA_ATENDIMENTO, AVL.DESCRICAO)
HAVING AVG(AVL.NOTA_ATENDIMENTO) > 6;


-- c. Informe o preço de compra médio (preço oferecido pelos fornecedores) e o preco
-- de venda do produto "Nescau Cereal", além do número de fornecedores que o fornecem.

SELECT AVG(PF.PRECO_COMPRA), PDT.PRECO_VENDA, COUNT(FNC.NRO_FORNECEDOR)
FROM PRODUTO_FORNECIDO PF
JOIN PRODUTO PDT ON PDT.NRO_PRODUTO = PF.NRO_PRODUTO
JOIN FORNECEDOR FNC ON FNC.NRO_FORNECEDOR = PF.NRO_FORNECEDOR
WHERE PDT.DESCRICAO = 'Nescau Cereal - 500g'
GROUP BY PDT.PRECO_VENDA;


-- d. Informe o CPF e nome do gerente, preço de compra e nome do produto e
-- sua quantidade dos pedidos de compra solicitados no mês de agosto de 2024.

SELECT GER.CPF_FUNCIONARIO, GER.NOME_GERENTE, PF.PRECO_COMPRA, PRD.DESCRICAO, CNT.QUANTIDADE
FROM GERENTE GER
JOIN SOLICITA SLC ON SLC.CPF_FUNCIONARIO = GER.CPF_FUNCIONARIO
JOIN PEDIDO_COMPRA PC ON PC.NRO_PEDIDO = SLC.NRO_PEDIDO
JOIN CONTEM CNT ON CNT.NRO_PEDIDO = PC.NRO_PEDIDO
JOIN PRODUTO_FORNECIDO PF ON PF.NRO_PRODUTO = CNT.NRO_PRODUTO
JOIN PRODUTO PRD ON PRD.NRO_PRODUTO = PF.NRO_PRODUTO
WHERE PC.DATA_ENTREGA >= '2024-09-01' AND
	  PC.DATA_ENTREGA <= '2024-09-30';


-- e. Informe o CPF dos clientes, o nome dos clientes e a quantidade comprada
-- de compras que incluem mais de 10 unidades do produto “Leite
-- Condensado – Moça”.

SELECT CLI.CPF, CLI.NOME_CLIENTE, INC.QUANTIDADE
FROM CLIENTE CLI
JOIN COMPRA CMP ON CMP.CPF_CLIENTE = CLI.CPF
JOIN INCLUI INC ON INC.NRO_CUPOM_FISCAL = CMP.NRO_CUPOM_FISCAL
JOIN PRODUTO PRD ON PRD.NRO_PRODUTO = INC.NRO_PRODUTO
WHERE PRD.DESCRICAO = 'Leite Condensado - 100g' AND
      INC.QUANTIDADE >= 10;


-- f. Informe o CNPJ e o nome dos fornecedores que fornecem produtos da
-- categoria “CEREAIS".

SELECT FNC.CNPJ, FNC.NOME_CONTATO
FROM FORNECEDOR FNC
JOIN PRODUTO_FORNECIDO PF ON PF.NRO_FORNECEDOR = FNC.NRO_FORNECEDOR
JOIN PRODUTO PRD ON PRD.NRO_PRODUTO = PF.NRO_PRODUTO
JOIN CATEGORIA CAT ON CAT.CODIGO_CATEGORIA = PRD.CODIGO_CATEGORIA
WHERE CAT.DESCRICAO = 'CEREAIS';


-- g. Informe o CPF do cliente, o nome do cliente, seus telefones de contato e
-- endereco de residência do cliente que tem o maior gasto anual da categoria Diamante.

SELECT CLI.CPF, CLI.NOME_CLIENTE, TC.TELEFONE, CLI.ENDERECO_RESIDENCIAL
FROM CLIENTE CLI
JOIN TELEFONE_CLIENTE TC ON TC.CPF_CLIENTE = CLI.CPF
WHERE CLI.NOME_CATEGORIA = 'Diamante' AND
      CLI.VALOR_GASTO_ANUAL = (SELECT MAX(CLI.VALOR_GASTO_ANUAL)
	                           FROM CLIENTE CLI);


-- h. Informe o nome e CPF do gerente, o nome e CPF dos atendentes de caixa
-- que possuem nota de atendimento menor que 4.

SELECT GER.NOME_GERENTE, GER.CPF_FUNCIONARIO, FNC.NOME, ATC.CPF_FUNCIONARIO
FROM GERENTE GER
JOIN FUNCIONARIO FNC ON FNC.CPF_GERENTE = GER.CPF_FUNCIONARIO
JOIN ATENDENTE_CAIXA ATC ON ATC.CPF_FUNCIONARIO = FNC.CPF
JOIN COMPRA CMP ON CMP.CPF_ATENDENTE = ATC.CPF_FUNCIONARIO
JOIN AVALIACAO AVA ON AVA.NRO_CUPOM_FISCAL = CMP.NRO_CUPOM_FISCAL
WHERE AVA.NOTA_ATENDIMENTO < 4;


-- i. Informe o CPF e nome dos repositores responsáveis pela sessão que
-- contém o produto “Energético Monster – 473ml”.

SELECT REP.CPF_FUNCIONARIO, FNC.NOME
FROM REPOSITOR REP
JOIN FUNCIONARIO FNC ON FNC.CPF = REP.CPF_FUNCIONARIO
JOIN RESPONSAVEL RES ON RES.CPF_REPOSITOR = REP.CPF_FUNCIONARIO
JOIN SESSAO SES ON SES.CODIGO_SESSAO = RES.CODIGO_SESSAO
JOIN PRODUTO PRD ON PRD.CODIGO_SESSAO = SES.CODIGO_SESSAO
WHERE PRD.DESCRICAO = 'Monster energético - 473ml';


-- j. Informe os telefones de contato e nome dos clientes que possuem cupons
-- de desconto com data de vencimento próximas de 1 mês da data de hoje.

SELECT CLI.NOME_CLIENTE, TC.TELEFONE
FROM CLIENTE CLI
JOIN TELEFONE_CLIENTE TC ON TC.CPF_CLIENTE = CLI.CPF
JOIN COMPRA CMP ON CMP.CPF_CLIENTE = CLI.CPF
JOIN CUPOM CUP ON CUP.NRO_CUPOM_FISCAL = CMP.NRO_CUPOM_FISCAL
WHERE CUP.DATA_VALIDADE > '2024-10-14' AND
      CUP.DATA_VALIDADE < '2024-11-14';



-- Atualizações:

-- a. Aumento do preço dos itens da categoria de bebidas (número 7) em 20%

SELECT CODIGO_CATEGORIA, PRECO_VENDA
FROM PRODUTO
WHERE CODIGO_CATEGORIA = 7;

UPDATE PRODUTO 
	SET PRECO_VENDA = PRECO_VENDA * 1.2
    WHERE CODIGO_CATEGORIA = 7;

SELECT CODIGO_CATEGORIA, PRECO_VENDA
FROM PRODUTO
WHERE CODIGO_CATEGORIA = 7;


-- b. Atualização do pedido de compra 757004 para a efetivação de pagamento após uma primeira tentativa
-- que havia dado errado:

SELECT DATA_EMISSAO, PREVISAO_ENTREGA, CONDICAO_PAGAMENTO, DEVOLUCAO, DATA_ENTREGA
FROM PEDIDO_COMPRA
WHERE NRO_PEDIDO = 757004;

UPDATE PEDIDO_COMPRA
SET DATA_EMISSAO = '2024-10-03',
    PREVISAO_ENTREGA = '2024-10-24',
	CONDICAO_PAGAMENTO = 'Efetuado',
	DATA_ENTREGA = '2024-10-23'
WHERE NRO_PEDIDO = 757004;

SELECT DATA_EMISSAO, PREVISAO_ENTREGA, CONDICAO_PAGAMENTO, DEVOLUCAO, DATA_ENTREGA
FROM PEDIDO_COMPRA
WHERE NRO_PEDIDO = 757004;