INSERT INTO FORNECEDOR(
	NRO_FORNECEDOR, CNPJ, NOME_CONTATO, DENOMINACAO_SOCIAL, PRAZO_ENTREGA, ENDERECO, CONDICOES_PAGAMENTO, BAIRRO, VALOR_TOTAL_ULTIMO_ANO, ESTADO, CEP, EMAIL, DESCONTOS, CIDADE)
	VALUES (1, '61068276000104', 'Mariana Santos', 'Nestlé Brasil Ltda.', 3, 'Av. das Nações Unidas, 17007', 'Dividido em até 12x', 'Várzea de Baixo', 8750000.00, 'SP', '04730-090', 'comercial@nestle.com.br', 4.50, 'São Paulo');

INSERT INTO FORNECEDOR(
	NRO_FORNECEDOR, CNPJ, NOME_CONTATO, DENOMINACAO_SOCIAL, PRAZO_ENTREGA, ENDERECO, CONDICOES_PAGAMENTO, BAIRRO, VALOR_TOTAL_ULTIMO_ANO, ESTADO, CEP, EMAIL, DESCONTOS, CIDADE)
	VALUES (2, '47508411000156', 'Ricardo Oliveira', 'Unilever Brasil Ltda.', 4, 'Av. Presidente Juscelino Kubitschek, 1309', 'Dividido em até 24x', 'Vila Nova Conceição', 7650000.00, 'SP', '04543-011', 'vendas@unilever.com.br', 5.00, 'São Paulo');

INSERT INTO FORNECEDOR(
	NRO_FORNECEDOR, CNPJ, NOME_CONTATO, DENOMINACAO_SOCIAL, PRAZO_ENTREGA, ENDERECO, CONDICOES_PAGAMENTO, BAIRRO, VALOR_TOTAL_ULTIMO_ANO, ESTADO, CEP, EMAIL, DESCONTOS, CIDADE)
	VALUES (3, '60746948000112', 'Patricia Lima', 'Procter & Gamble Brasil', 5, 'Rua Francisco Tramontano, 80', 'Dividido em até 12x', 'Morumbi', 6920000.00, 'SP', '05686-010', 'comercial@pg.com.br', 4.75, 'São Paulo');

INSERT INTO FORNECEDOR(
	NRO_FORNECEDOR, CNPJ, NOME_CONTATO, DENOMINACAO_SOCIAL, PRAZO_ENTREGA, ENDERECO, CONDICOES_PAGAMENTO, BAIRRO, VALOR_TOTAL_ULTIMO_ANO, ESTADO, CEP, EMAIL, DESCONTOS, CIDADE)
	VALUES (4, '92754738000162', 'Fernando Costa', 'Coca-Cola FEMSA Brasil', 2, 'Rua Desenvolimento, 1200', 'Dividido em até 6x', 'Industrial', 9200000.00, 'SP', '06543-001', 'vendas@cocacola.com.br', 5.50, 'Jundiaí');

INSERT INTO FORNECEDOR(
	NRO_FORNECEDOR, CNPJ, NOME_CONTATO, DENOMINACAO_SOCIAL, PRAZO_ENTREGA, ENDERECO, CONDICOES_PAGAMENTO, BAIRRO, VALOR_TOTAL_ULTIMO_ANO, ESTADO, CEP, EMAIL, DESCONTOS, CIDADE)
	VALUES (5, '33000167000101', 'Lucas Martins', 'Ambev S.A.', 2, 'Rua Dr. Renato Paes de Barros, 1017', 'Dividido em até 16x', 'Itaim Bibi', 8850000.00, 'SP', '04530-001', 'comercial@ambev.com.br', 4.25, 'São Paulo');

INSERT INTO FORNECEDOR(
	NRO_FORNECEDOR, CNPJ, NOME_CONTATO, DENOMINACAO_SOCIAL, PRAZO_ENTREGA, ENDERECO, CONDICOES_PAGAMENTO, BAIRRO, VALOR_TOTAL_ULTIMO_ANO, ESTADO, CEP, EMAIL, DESCONTOS, CIDADE)
	VALUES (6, '59104760000191', 'Gabriela Silva', 'Seara Alimentos Ltda.', 3, 'Av. Marginal Direita do Tietê, 500', 'Dividido em até 18x', 'Vila Jaguara', 6350000.00, 'SP', '05118-100', 'vendas@seara.com.br', 4.00, 'São Paulo');

INSERT INTO FORNECEDOR(
	NRO_FORNECEDOR, CNPJ, NOME_CONTATO, DENOMINACAO_SOCIAL, PRAZO_ENTREGA, ENDERECO, CONDICOES_PAGAMENTO, BAIRRO, VALOR_TOTAL_ULTIMO_ANO, ESTADO, CEP, EMAIL, DESCONTOS, CIDADE)
	VALUES (7, '84429695000111', 'Roberto Santos', 'Kimberly-Clark Brasil', 4, 'Av. das Nações Unidas, 8501', 'Dividido em até 12x', 'Pinheiros', 5980000.00, 'SP', '05425-070', 'comercial@kcc.com.br', 4.80, 'São Paulo');

INSERT INTO FORNECEDOR(
	NRO_FORNECEDOR, CNPJ, NOME_CONTATO, DENOMINACAO_SOCIAL, PRAZO_ENTREGA, ENDERECO, CONDICOES_PAGAMENTO, BAIRRO, VALOR_TOTAL_ULTIMO_ANO, ESTADO, CEP, EMAIL, DESCONTOS, CIDADE)
	VALUES (8, '60498706000157', 'Ana Ferreira', 'Colgate-Palmolive Brasil', 3, 'Rua Rio Grande, 1219', 'Dividido em até 12x', 'Vila Mariana', 4950000.00, 'SP', '04018-030', 'vendas@colgate.com.br', 4.60, 'São Paulo');

INSERT INTO FORNECEDOR(
	NRO_FORNECEDOR, CNPJ, NOME_CONTATO, DENOMINACAO_SOCIAL, PRAZO_ENTREGA, ENDERECO, CONDICOES_PAGAMENTO, BAIRRO, VALOR_TOTAL_ULTIMO_ANO, ESTADO, CEP, EMAIL, DESCONTOS, CIDADE)
	VALUES (9, '97837181000147', 'Carlos Eduardo', 'Pepsico do Brasil Ltda.', 3, 'Av. Francisco Matarazzo, 1400', 'Dividido em até 20x', 'Água Branca', 7150000.00, 'SP', '05001-100', 'comercial@pepsico.com.br', 5.20, 'São Paulo');

INSERT INTO FORNECEDOR(
	NRO_FORNECEDOR, CNPJ, NOME_CONTATO, DENOMINACAO_SOCIAL, PRAZO_ENTREGA, ENDERECO, CONDICOES_PAGAMENTO, BAIRRO, VALOR_TOTAL_ULTIMO_ANO, ESTADO, CEP, EMAIL, DESCONTOS, CIDADE)
	VALUES (10, '45997418000154', 'Julia Mendes', 'BRF Brasil Foods', 2, 'Rua Hungria, 1400', 'Dividido em até 4x', 'Jardim Europa', 8120000.00, 'SP', '01455-000', 'vendas@brf.com.br', 4.90, 'São Paulo');
	
SELECT * FROM FORNECEDOR;