
INSERT INTO SESSAO(CODIGO_SESSAO, NOME)
	VALUES (1, 'Frios e Embutidos');

INSERT INTO SESSAO(CODIGO_SESSAO, NOME)
	VALUES (2, 'Açougue');

INSERT INTO SESSAO(CODIGO_SESSAO, NOME)
	VALUES (3, 'Hortifruti');

INSERT INTO SESSAO(CODIGO_SESSAO, NOME)
	VALUES (4, 'Lactinios');

INSERT INTO SESSAO(CODIGO_SESSAO, NOME)
	VALUES (5, 'Congelados');

INSERT INTO SESSAO(CODIGO_SESSAO, NOME)
	VALUES (6, 'Limpeza');

INSERT INTO SESSAO(CODIGO_SESSAO, NOME)
	VALUES (7, 'Higiene e Beleza');

INSERT INTO SESSAO(CODIGO_SESSAO, NOME)
	VALUES (8, 'Bebidas');

INSERT INTO SESSAO(CODIGO_SESSAO, NOME)
	VALUES (9, 'Padaria');

INSERT INTO SESSAO(CODIGO_SESSAO, NOME)
	VALUES (10, 'Cereais e Matinais');

SELECT * FROM SESSAO;