INSERT INTO PRODUTO(
	NRO_PRODUTO, MEDIA_VENDAS_MES, SESSAO_GONDOLA, DESCRICAO, NOME_FABRICANTE, UNIDADE_VENDA, PRECO_VENDA, CODIGO_SESSAO, CODIGO_CATEGORIA, QUANTIDADE)
	VALUES (1, 3532, 1, 'Leite Condensado - 100g', 'Moça', 'g', 6.99, 4, 8, 500);

INSERT INTO PRODUTO(
	NRO_PRODUTO, MEDIA_VENDAS_MES, SESSAO_GONDOLA, DESCRICAO, NOME_FABRICANTE, UNIDADE_VENDA, PRECO_VENDA, CODIGO_SESSAO, CODIGO_CATEGORIA, QUANTIDADE)
	VALUES (2, 12437, 3, 'Monster energético - 473ml', 'Monster energy', 'ml', 8.49, 8, 7, 300);

INSERT INTO PRODUTO(
	NRO_PRODUTO, MEDIA_VENDAS_MES, SESSAO_GONDOLA, DESCRICAO, NOME_FABRICANTE, UNIDADE_VENDA, PRECO_VENDA, CODIGO_SESSAO, CODIGO_CATEGORIA, QUANTIDADE)
	VALUES (3, 8341, 7, 'Nescau Cereal - 500g', 'Nescau', 'g', 15.99, 10, 10, 400);

INSERT INTO PRODUTO(
	NRO_PRODUTO, MEDIA_VENDAS_MES, SESSAO_GONDOLA, DESCRICAO, NOME_FABRICANTE, UNIDADE_VENDA, PRECO_VENDA, CODIGO_SESSAO, CODIGO_CATEGORIA, QUANTIDADE)
	VALUES (4, 345, 2, 'Pasta de dentes Colgate - 150g', 'Moça', 'g', 7.49, 7, 5, 600);

INSERT INTO PRODUTO(
	NRO_PRODUTO, MEDIA_VENDAS_MES, SESSAO_GONDOLA, DESCRICAO, NOME_FABRICANTE, UNIDADE_VENDA, PRECO_VENDA, CODIGO_SESSAO, CODIGO_CATEGORIA, QUANTIDADE)
	VALUES (5, 13542, 13, 'Detergente Ype Neutro - 500ml', 'YPE', 'ml', 2.99, 6, 2, 800);

INSERT INTO PRODUTO(
	NRO_PRODUTO, MEDIA_VENDAS_MES, SESSAO_GONDOLA, DESCRICAO, NOME_FABRICANTE, UNIDADE_VENDA, PRECO_VENDA, CODIGO_SESSAO, CODIGO_CATEGORIA, QUANTIDADE)
	VALUES (6, 1223, 4, 'Requeijão Auroroa - 200g', 'Aurora', 'g', 6.99, 4, 8, 300);

INSERT INTO PRODUTO(
	NRO_PRODUTO, MEDIA_VENDAS_MES, SESSAO_GONDOLA, DESCRICAO, NOME_FABRICANTE, UNIDADE_VENDA, PRECO_VENDA, CODIGO_SESSAO, CODIGO_CATEGORIA, QUANTIDADE)
	VALUES (7, 3542, 3, 'Presunto Sadia - 200g', 'Sadia', 'g', 4.99, 1, 9, 400);

INSERT INTO PRODUTO(
	NRO_PRODUTO, MEDIA_VENDAS_MES, SESSAO_GONDOLA, DESCRICAO, NOME_FABRICANTE, UNIDADE_VENDA, PRECO_VENDA, CODIGO_SESSAO, CODIGO_CATEGORIA, QUANTIDADE)
	VALUES (8, 752, 2, 'Peito de frango 1KG - Seara', 'Seara', 'kg', 15.49, 5, 1, 200);

INSERT INTO PRODUTO(
	NRO_PRODUTO, MEDIA_VENDAS_MES, SESSAO_GONDOLA, DESCRICAO, NOME_FABRICANTE, UNIDADE_VENDA, PRECO_VENDA, CODIGO_SESSAO, CODIGO_CATEGORIA, QUANTIDADE)
	VALUES (9, 352, 1, 'Picanha 1KG - Friboi', 'Friboi', 'g', 86.19, 2, 1, 100);

INSERT INTO PRODUTO(
	NRO_PRODUTO, MEDIA_VENDAS_MES, SESSAO_GONDOLA, DESCRICAO, NOME_FABRICANTE, UNIDADE_VENDA, PRECO_VENDA, CODIGO_SESSAO, CODIGO_CATEGORIA, QUANTIDADE)
	VALUES (10, 352, 1, 'Cerveja lata 350ml - Skoll', 'Skoll', 'ml', 5.49, 8, 6, 900);

SELECT * FROM PRODUTO;
