INSERT INTO PARTICIPA(
    NRO_PRODUTO, CODIGO_PROMOCAO, VALOR_DESCONTO, VALOR_DESCONTO_PRATA, VALOR_DESCONTO_OURO, VALOR_DESCONTO_DIAMANTE)
    VALUES (10, 2, 0.50, 1.00, 1.50, 2.00); -- Cerveja Skol no Festival de Cervejas

INSERT INTO PARTICIPA(
    NRO_PRODUTO, CODIGO_PROMOCAO, VALOR_DESCONTO, VALOR_DESCONTO_PRATA, VALOR_DESCONTO_OURO, VALOR_DESCONTO_DIAMANTE)
    VALUES (8, 5, 2.50, 3.00, 3.50, 4.00); -- Peito de frango Seara no Festival de Carnes

INSERT INTO PARTICIPA(
    NRO_PRODUTO, CODIGO_PROMOCAO, VALOR_DESCONTO, VALOR_DESCONTO_PRATA, VALOR_DESCONTO_OURO, VALOR_DESCONTO_DIAMANTE)
    VALUES (9, 5, 15.00, 18.00, 20.00, 25.00); -- Picanha Friboi no Festival de Carnes

INSERT INTO PARTICIPA(
    NRO_PRODUTO, CODIGO_PROMOCAO, VALOR_DESCONTO, VALOR_DESCONTO_PRATA, VALOR_DESCONTO_OURO, VALOR_DESCONTO_DIAMANTE)
    VALUES (5, 7, 0.30, 0.50, 0.80, 1.00); -- Detergente Ypê na Limpeza em Dobro

INSERT INTO PARTICIPA(
    NRO_PRODUTO, CODIGO_PROMOCAO, VALOR_DESCONTO, VALOR_DESCONTO_PRATA, VALOR_DESCONTO_OURO, VALOR_DESCONTO_DIAMANTE)
    VALUES (3, 8, 3.00, 3.50, 4.00, 5.00); -- Nescau Cereal no Festival de Chocolates

INSERT INTO PARTICIPA(
    NRO_PRODUTO, CODIGO_PROMOCAO, VALOR_DESCONTO, VALOR_DESCONTO_PRATA, VALOR_DESCONTO_OURO, VALOR_DESCONTO_DIAMANTE)
    VALUES (2, 9, 1.50, 2.00, 2.50, 3.00); -- Monster no Verão Refrescante

INSERT INTO PARTICIPA(
    NRO_PRODUTO, CODIGO_PROMOCAO, VALOR_DESCONTO, VALOR_DESCONTO_PRATA, VALOR_DESCONTO_OURO, VALOR_DESCONTO_DIAMANTE)
    VALUES (1, 1, 1.00, 1.50, 2.00, 2.50); -- Leite Condensado na Black Friday

INSERT INTO PARTICIPA(
    NRO_PRODUTO, CODIGO_PROMOCAO, VALOR_DESCONTO, VALOR_DESCONTO_PRATA, VALOR_DESCONTO_OURO, VALOR_DESCONTO_DIAMANTE)
    VALUES (4, 1, 1.50, 2.00, 2.50, 3.00); -- Pasta de dentes na Black Friday

INSERT INTO PARTICIPA(
    NRO_PRODUTO, CODIGO_PROMOCAO, VALOR_DESCONTO, VALOR_DESCONTO_PRATA, VALOR_DESCONTO_OURO, VALOR_DESCONTO_DIAMANTE)
    VALUES (6, 1, 1.20, 1.70, 2.20, 2.70); -- Requeijão na Black Friday

INSERT INTO PARTICIPA(
    NRO_PRODUTO, CODIGO_PROMOCAO, VALOR_DESCONTO, VALOR_DESCONTO_PRATA, VALOR_DESCONTO_OURO, VALOR_DESCONTO_DIAMANTE)
    VALUES (7, 1, 1.00, 1.50, 2.00, 2.50); -- Presunto na Black Friday
	
SELECT * FROM PARTICIPA;