INSERT INTO PRODUTO_FORNECIDO (NRO_PRODUTO, NRO_FORNECEDOR, PRECO_COMPRA)
VALUES (1, 1, 5.49);

INSERT INTO PRODUTO_FORNECIDO (NRO_PRODUTO, NRO_FORNECEDOR, PRECO_COMPRA)
VALUES (2, 4, 7.00);

INSERT INTO PRODUTO_FORNECIDO (NRO_PRODUTO, NRO_FORNECEDOR, PRECO_COMPRA)
VALUES (3, 1, 13.50);

INSERT INTO PRODUTO_FORNECIDO (NRO_PRODUTO, NRO_FORNECEDOR, PRECO_COMPRA)
VALUES (4, 8, 5.99);

INSERT INTO PRODUTO_FORNECIDO (NRO_PRODUTO, NRO_FORNECEDOR, PRECO_COMPRA)
VALUES (5, 2, 2.49);

INSERT INTO PRODUTO_FORNECIDO (NRO_PRODUTO, NRO_FORNECEDOR, PRECO_COMPRA)
VALUES (6, 6, 5.50);

INSERT INTO PRODUTO_FORNECIDO (NRO_PRODUTO, NRO_FORNECEDOR, PRECO_COMPRA)
VALUES (7, 3, 3.99);

INSERT INTO PRODUTO_FORNECIDO (NRO_PRODUTO, NRO_FORNECEDOR, PRECO_COMPRA)
VALUES (8, 6, 12.99);

INSERT INTO PRODUTO_FORNECIDO (NRO_PRODUTO, NRO_FORNECEDOR, PRECO_COMPRA)
VALUES (9, 9, 75.00);

INSERT INTO PRODUTO_FORNECIDO (NRO_PRODUTO, NRO_FORNECEDOR, PRECO_COMPRA)
VALUES (10, 5, 4.50);

SELECT * FROM PRODUTO_FORNECIDO;