INSERT INTO CATEGORIA_CLIENTE (NOME_CATEGORIA, PISO_GASTO_ANUAL)
VALUES ('Diamante', 8000);

INSERT INTO CATEGORIA_CLIENTE (NOME_CATEGORIA, PISO_GASTO_ANUAL)
VALUES ('Ouro', 5000);

INSERT INTO CATEGORIA_CLIENTE (NOME_CATEGORIA, PISO_GASTO_ANUAL)
VALUES ('Prata', 3000);

INSERT INTO CATEGORIA_CLIENTE (NOME_CATEGORIA, PISO_GASTO_ANUAL)
VALUES ('Padrão', 0);

SELECT * FROM CATEGORIA_CLIENTE;