INSERT INTO CLIENTE (CPF, NOME_CLIENTE, ENDERECO_RESIDENCIAL, DATA_NASCIMENTO, PROFISSAO,
VALOR_GASTO_ANUAL, NOME_CATEGORIA)
VALUES (70480360448, 'Carlos Martins Chagas', 'Rua Coelho Neto, 197, Tabajaras',
'1974-11-27', 'Farmacêutico', '5500', 'Ouro');

INSERT INTO CLIENTE (CPF, NOME_CLIENTE, ENDERECO_RESIDENCIAL, DATA_NASCIMENTO, PROFISSAO,
VALOR_GASTO_ANUAL, NOME_CATEGORIA)
VALUES (67412966898, 'Martim Gomes Pereira', 'Rua Nelson de Oliveira, 476, Santa Mônica',
'1996-05-15', 'Professor de Educação Física', '6425', 'Ouro');

INSERT INTO CLIENTE (CPF, NOME_CLIENTE, ENDERECO_RESIDENCIAL, DATA_NASCIMENTO, PROFISSAO,
VALOR_GASTO_ANUAL, NOME_CATEGORIA)
VALUES (42985409799, 'Eduarda Azevedo Gontijo', 'Rua dos Pica-Paus, 1750, Nova Uberlândia',
'2000-06-09', 'Estudante', '2842', 'Padrão');

INSERT INTO CLIENTE (CPF, NOME_CLIENTE, ENDERECO_RESIDENCIAL, DATA_NASCIMENTO, PROFISSAO,
VALOR_GASTO_ANUAL, NOME_CATEGORIA)
VALUES (53731788020, 'Melissa Rodrigues Caxeta', 'Av. Pará, 157, Brasil',
'1984-10-23', 'Consultora de Marketing', '3687', 'Prata');

INSERT INTO CLIENTE (CPF, NOME_CLIENTE, ENDERECO_RESIDENCIAL, DATA_NASCIMENTO, PROFISSAO,
VALOR_GASTO_ANUAL, NOME_CATEGORIA)
VALUES (47154167009, 'Rodrigo Pereira da Silva', 'Rua das Acácias, 514, Cidade Jardim',
'1966-03-27', 'Arquiteto', '8143', 'Diamante');

INSERT INTO CLIENTE (CPF, NOME_CLIENTE, ENDERECO_RESIDENCIAL, DATA_NASCIMENTO, PROFISSAO,
VALOR_GASTO_ANUAL, NOME_CATEGORIA)
VALUES (29792552545, 'Victor Silva Costa', 'Rua dos Sabiás, 491, Cidade Jardim',
'1967-04-24', 'Engenheiro Civil', '9652', 'Diamante');

INSERT INTO CLIENTE (CPF, NOME_CLIENTE, ENDERECO_RESIDENCIAL, DATA_NASCIMENTO, PROFISSAO,
VALOR_GASTO_ANUAL, NOME_CATEGORIA)
VALUES (85644566137, 'Marisa Melo Oliveira', 'Rua Denver, 191, Novo Mundo',
'1984-08-06', 'Nutricionista', '6933', 'Ouro');

INSERT INTO CLIENTE (CPF, NOME_CLIENTE, ENDERECO_RESIDENCIAL, DATA_NASCIMENTO, PROFISSAO,
VALOR_GASTO_ANUAL, NOME_CATEGORIA)
VALUES (46212763798, 'Sarah Macedo Lima', 'Rua Antônio Morais, 637, Cazeca',
'1945-02-01', 'Aposentada', '4021', 'Prata');

INSERT INTO CLIENTE (CPF, NOME_CLIENTE, ENDERECO_RESIDENCIAL, DATA_NASCIMENTO, PROFISSAO,
VALOR_GASTO_ANUAL, NOME_CATEGORIA)
VALUES (27805008329, 'Douglas Rocha Mascarenha', 'Rua dos Pereira, 138, Centro',
'2001-01-18', 'Estudante', '3641', 'Prata');

INSERT INTO CLIENTE (CPF, NOME_CLIENTE, ENDERECO_RESIDENCIAL, DATA_NASCIMENTO, PROFISSAO,
VALOR_GASTO_ANUAL, NOME_CATEGORIA)
VALUES (65535046361, 'Beatriz Cunha Pacheco', 'Rua Arlindo Gomes Rodrigues, 1644, Martins',
'1943-06-11', 'Aposentada', '7436', 'Ouro');

SELECT * FROM CLIENTE;