INSERT INTO INCLUI (NRO_PRODUTO, NRO_CUPOM_FISCAL, QUANTIDADE, DESCONTO_APLICADO) 
    VALUES (1, 937991, 10, 5.00);
    
INSERT INTO INCLUI (NRO_PRODUTO, NRO_CUPOM_FISCAL, QUANTIDADE, DESCONTO_APLICADO) 
    VALUES (2, 937991, 5, 10.00);
    
INSERT INTO INCLUI (NRO_PRODUTO, NRO_CUPOM_FISCAL, QUANTIDADE, DESCONTO_APLICADO) 
    VALUES (3, 937991, 3, 3.00);
    
INSERT INTO INCLUI (NRO_PRODUTO, NRO_CUPOM_FISCAL, QUANTIDADE, DESCONTO_APLICADO) 
    VALUES (4, 723524, 2, 1.50);
    
INSERT INTO INCLUI (NRO_PRODUTO, NRO_CUPOM_FISCAL, QUANTIDADE, DESCONTO_APLICADO) 
    VALUES (5, 723524, 4, 2.00);
    
INSERT INTO INCLUI (NRO_PRODUTO, NRO_CUPOM_FISCAL, QUANTIDADE, DESCONTO_APLICADO) 
    VALUES (6, 463729, 7, 0.00);
    
INSERT INTO INCLUI (NRO_PRODUTO, NRO_CUPOM_FISCAL, QUANTIDADE, DESCONTO_APLICADO) 
    VALUES (7, 463729, 10, 0.00);
    
INSERT INTO INCLUI (NRO_PRODUTO, NRO_CUPOM_FISCAL, QUANTIDADE, DESCONTO_APLICADO) 
    VALUES (8, 185175, 5, 2.00);
    
INSERT INTO INCLUI (NRO_PRODUTO, NRO_CUPOM_FISCAL, QUANTIDADE, DESCONTO_APLICADO) 
    VALUES (9, 185175, 1, 0.80);
    
INSERT INTO INCLUI (NRO_PRODUTO, NRO_CUPOM_FISCAL, QUANTIDADE, DESCONTO_APLICADO) 
    VALUES (10, 163228, 20, 6.00);
    
INSERT INTO INCLUI (NRO_PRODUTO, NRO_CUPOM_FISCAL, QUANTIDADE, DESCONTO_APLICADO) 
    VALUES (1, 163228, 2, 2.90);
    
INSERT INTO INCLUI (NRO_PRODUTO, NRO_CUPOM_FISCAL, QUANTIDADE, DESCONTO_APLICADO) 
    VALUES (2, 460547, 8, 1.17);
    
INSERT INTO INCLUI (NRO_PRODUTO, NRO_CUPOM_FISCAL, QUANTIDADE, DESCONTO_APLICADO) 
    VALUES (3, 460547, 3, 1.00);
    
INSERT INTO INCLUI (NRO_PRODUTO, NRO_CUPOM_FISCAL, QUANTIDADE, DESCONTO_APLICADO) 
    VALUES (4, 915663, 10, 5.00);
    
INSERT INTO INCLUI (NRO_PRODUTO, NRO_CUPOM_FISCAL, QUANTIDADE, DESCONTO_APLICADO) 
    VALUES (5, 915663, 2, 0.00);
    
INSERT INTO INCLUI (NRO_PRODUTO, NRO_CUPOM_FISCAL, QUANTIDADE, DESCONTO_APLICADO) 
    VALUES (6, 302841, 3, 2.50);
    
INSERT INTO INCLUI (NRO_PRODUTO, NRO_CUPOM_FISCAL, QUANTIDADE, DESCONTO_APLICADO) 
    VALUES (7, 302841, 5, 3.00);
    
INSERT INTO INCLUI (NRO_PRODUTO, NRO_CUPOM_FISCAL, QUANTIDADE, DESCONTO_APLICADO) 
    VALUES (8, 532202, 1, 0.00);
    
INSERT INTO INCLUI (NRO_PRODUTO, NRO_CUPOM_FISCAL, QUANTIDADE, DESCONTO_APLICADO) 
    VALUES (9, 532202, 6, 0.00);
    
INSERT INTO INCLUI (NRO_PRODUTO, NRO_CUPOM_FISCAL, QUANTIDADE, DESCONTO_APLICADO) 
    VALUES (10, 973711, 5, 6.00);
    
INSERT INTO INCLUI (NRO_PRODUTO, NRO_CUPOM_FISCAL, QUANTIDADE, DESCONTO_APLICADO) 
    VALUES (1, 147920, 8, 1.00);
    
INSERT INTO INCLUI (NRO_PRODUTO, NRO_CUPOM_FISCAL, QUANTIDADE, DESCONTO_APLICADO) 
    VALUES (2, 280662, 4, 4.50);
    
INSERT INTO INCLUI (NRO_PRODUTO, NRO_CUPOM_FISCAL, QUANTIDADE, DESCONTO_APLICADO) 
    VALUES (3, 280662, 9, 3.00);
    
INSERT INTO INCLUI (NRO_PRODUTO, NRO_CUPOM_FISCAL, QUANTIDADE, DESCONTO_APLICADO) 
    VALUES (4, 300795, 5, 2.26);
    
INSERT INTO INCLUI (NRO_PRODUTO, NRO_CUPOM_FISCAL, QUANTIDADE, DESCONTO_APLICADO) 
    VALUES (5, 300795, 7, 1.00);
    
SELECT * FROM INCLUI;